paypal/urls.py
from django.urls import path

from . import views

app_name = 'paypal'

urlpatterns = [
    path('sp1/paypal-payment/', views.make_paypal_payment, name='make_paypal_payment'),
    path('sp1/payment-return/', views.payment_return, name='payment_return'),
    path('sp1/payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('sp1/payment-success/', views.payment_success, name='payment_success'),
    path('sp1/payment-failure/', views.payment_failure, name='payment_failure'),

    # braintree
    path('generate-client-token/', views.GenerateClientTokenView.as_view(), name='generate_client_token'),
    path('execute-payment/', views.execute_payment, name='execute_payment'),

]

paypalclient/urls.py
from django.urls import path

from . import views

app_name = 'paypalclient'

urlpatterns = [
    path('sp1/client-payment/', views.paypal_client_payment, name='paypal_client_payment'),
    path('sp1/capture-payment/', views.capture_payment, name='capture_payment'),
    path('sp1/payment-success/', views.payment_success, name='payment_success'),
    path('sp1/payment-failure/', views.payment_failure, name='payment_failure'),
]

spymate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('paypal/', include('paypal.urls', namespace='paypal')),
    path('paypalclient/', include('paypalclient.urls', namespace='paypalclient')),
]

paypalclient/models.py
from django.db import models

# Create your models here.

paypalclient/views.py
from django.shortcuts import render
from django.urls import reverse
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from paypalcheckoutsdk.orders import OrdersCaptureRequest
from django.contrib.auth.models import User
import json

from .paypal import PayPalClient
from frontend.models import Payment
from frontend.send_email import send_html_email


def paypal_client_payment(request):

    client_id = settings.PAYPAL_CLIENT_ID

    context = {'client_id':client_id}
    return render(request, 'paypalclient/payment_client.html', context)


@csrf_exempt
def capture_payment(request):
    if request.method == 'POST':
        PPClient = PayPalClient()
        data = json.loads(request.body)
        order_id = data.get('orderID')
        name = data.get('name')
        phone = data.get('phone')
        email = data.get('email')

        # url success and failure
        success_url = request.build_absolute_uri(reverse('paypalclient:payment_success'))
        failure_url = request.build_absolute_uri(reverse('paypalclient:payment_failure'))

        # Capture the payment using PayPal Python SDK
        order_request = OrdersCaptureRequest(order_id)
        response = PPClient.client.execute(order_request)

        # Handle response from PayPal
        if response.result.status == 'COMPLETED':
            # create a new payment instance
            new_payment = Payment.objects.create(ref=order_id, name=name, email=email, phone=phone, is_success = True)

            # create user account
            password_one = new_payment.email.split("@")[0]
            password_two = new_payment.phone[2:8]
            d_ref = new_payment.ref[:13]
            main_password = f'{password_one}{password_two}@@'
            main_username = f"{password_one}-{d_ref}"

            new_user = User.objects.create_user(username=main_username, email=new_payment.email, password=main_password)

            # email contents
            subject = "Your lifetime access to spymate has been approved."
            html_template = 'emails/success_purchase_email.html'
            context = {
                'subject': subject,
                'name': new_payment.name,
                'username': main_username,
                'password': main_password
            }

            # sending email
            try:
                send_html_email(subject, html_template, context, new_payment.email)
            except:
                pass
            payer_name = response.result.payer.name.given_name
            return JsonResponse({'status': 'success', 'payerName': payer_name,
                                'success_url':success_url})
        else:
            # Payment capture failed
            return JsonResponse({'status': 'error', 'message': 'Failed to capture payment.', 'failure_url':failure_url})

    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})


def payment_success(request):
    return render(request, 'paypalclient/payment_success.html')

def payment_failure(request):
    return render(request, 'paypalclient/payment_failure.html')

templates/paypalclient/payment_client.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<!-- <script src="https://www.paypal.com/sdk/js?client-id={{client_id}}&currency=USD&components=buttons&enable-funding=venmo&debug=true"></script> -->

<style>
    .currency-conversion-details p{
        color: #fff !important;
    }
    .currency-conversion{
        color: #fff !important;
    }
</style>

<!-- payment start -->
<div class="payment__container">
    <div class="payment__wrapper__small">
        <h1 class="text-center" id="logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
        <div class="payment__form__information">
            <div class="card bg-dark mt-5 mb-5" style="position: relative;">
                <div class="overlay_spinner">
                    <i class="fa-solid fa-spinner fa-spin"></i>
                </div>
                <div class="card-body">
                    <h5 class="text-center text-white">Fill the form below to continue</h5>
                    <hr style="border-color: white;">
                    <h2 class="text-white p__type">$15.00</h2>
                    <hr style="border-color: white;">
                    <form action="." id="paymentForm" method="post" class="mt-3">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="full_name" class="form-label text-white">Name</label>
                            <input type="text" name="full_name" class="form-control" id="full_name" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label text-white">Email</label>
                            <input type="email" name="email" class="form-control" id="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone_number" class="form-label text-white">Phone Number</label>
                            <input type="text" name="phone_number" class="form-control" id="phone_number">
                        </div>
                        
                        <hr style="border-color: white;">
                        <div class="paypal-side bg-light py-3 px-2">
                            <!-- PayPal Checkout buttons -->
                            <div id="paypal-button-container"></div>
                        </div>
                        
                        
                        <!-- <button type="submit" class="payment__btn" id="payment__btn">Continue</button> -->
                    </form>
                </div>
            </div>        
        </div>
        
    </div>
</div>
<!-- payment end -->

<script src="https://www.paypal.com/sdk/js?client-id={{client_id}}&currency=USD&components=buttons&enable-funding=venmo"></script>
<script>
    // Render the PayPal button into #paypal-button-container
    document.addEventListener('DOMContentLoaded', function () {

        paypal.Buttons({
            style: {
                label: 'pay',
                color: 'gold', // Customize text color
                shape: 'pill', // Choose pill/rect
                height: 40
            },
            createOrder: function(data, actions) {
                const form = document.getElementById('paymentForm');
                if (!form.checkValidity()) {
                    form.reportValidity();
                    return; // Stop further execution if form is not valid
                }
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '15.00', // Sample amount (replace with dynamic value)
                        }
                    }]
                });
            },
            onApprove: function(data, actions) {
                // Send a fetch API request to Django backend to process payment capture
                const form = document.getElementById('paymentForm');

                // Proceed with payment capture
                let formData = new FormData(form);
                let name = formData.get('full_name');
                let phone = formData.get('phone_number');
                let email = formData.get('email');
                const overlaySpinner = document.querySelector('.overlay_spinner');
                
                overlaySpinner.style.display = 'flex';
                return fetch('{% url "paypalclient:capture_payment" %}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        orderID: data.orderID,
                        name: name,
                        phone: phone,
                        email: email
                    }),
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        // alert('Transaction completed by ' + data.payerName);
                        // Example: redirect to a thank-you page
                        console.log(data.success_url)
                        window.location.href = data.success_url;
                        
                    } else {
                        // alert('Transaction failed. Please try again.');
                        console.log(data.failure_url)
                        window.location.href = data.failure_url;
                    }
                })
                .catch((error) => {
                    console.error('Error:', error);
                    alert('Transaction failed. Please try again.');
                });
            }
        }).render('#paypal-button-container');

    })
    
</script>
{% endblock %}

templates/paypalclient/payment_failure.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: rgb(128, 0, 0);
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
    .payment__btn{
        text-decoration: none;
        padding: 10px 130px;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-exclamation"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Failed</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your Payment failed, might be due<br>to insufficient balance or network error, but don't worry, you can try again</p>
                <p class="text-center">click the button below to try again</p>
                <a href="{% url 'paypalclient:paypal_client_payment' %}" class="payment__btn">Make Payment</a>
                <p class="text-center small mt-4">if the problem persist, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/paypalclient/payment_success.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: green;
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-check"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Successfull</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your Payment is successful, please check <br>your email for your login details to be able to continue using our service. </p>
                <p class="text-center">Thank you for trusting us.</p>
                <p class="text-center">If you don't receive an email, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/paypalclient/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PayPal JS SDK Standard Integration</title>
  </head>
  <body>
    <div id="paypal-button-container"></div>
    <p id="result-message"></p>
    
    <!-- Initialize the JS-SDK -->
    <script
      src="https://www.paypal.com/sdk/js?client-id=test&buyer- 
      country=US&currency=USD&components=buttons&enable-funding=venmo"
      data-sdk-integration-source="developer-studio"
    ></script>
    <script src="app.js"></script>
    
  </body>
</html>