paypal/urls.py
from django.urls import path

from . import views

app_name = 'paypal'

urlpatterns = [
    path('sp1/paypal-payment/', views.make_paypal_payment, name='make_paypal_payment'),
    path('sp1/payment-return/', views.payment_return, name='payment_return'),
    path('sp1/payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('sp1/payment-success/', views.payment_success, name='payment_success'),
    path('sp1/payment-failure/', views.payment_failure, name='payment_failure'),

    # braintree
    path('generate-client-token/', views.GenerateClientTokenView.as_view(), name='generate_client_token'),
    path('execute-payment/', views.execute_payment, name='execute_payment'),

]

spymate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('paypal/', include('paypal.urls', namespace='paypal')),
    path('paypalclient/', include('paypalclient.urls', namespace='paypalclient')),
]

paypal/views.py
import logging
from django.shortcuts import render, redirect
from django.urls import reverse
from .paypal_services import PayPalPaymentService, PayPalWebhookService
from django.http import JsonResponse, HttpResponseBadRequest
from django.conf import settings

from frontend.payment_type import generate_tx_ref
from frontend.models import Payment
from django.contrib.auth.models import User


logger = logging.getLogger(__name__)


def make_paypal_payment(request):
    if request.method == 'POST':
        selected_payment = request.POST.get('paymentType', None)
        name = request.POST.get('full_name', None)
        email = request.POST.get('email', None)
        phone_number = request.POST.get('phone_number', None)
        return_url = request.build_absolute_uri(reverse('paypal:payment_return'))
        cancel_url = request.build_absolute_uri(reverse('paypal:payment_cancel'))

        new_payment = Payment.objects.create(ref=generate_tx_ref(), name=name, email=email, phone=phone_number)

        if selected_payment:
            if selected_payment == 'paypal':  
                # constructing a payment data
                payment_data = {
                    "intent": "sale",
                    "payer": {
                        "payment_method": "paypal"
                    },
                    "transactions": [
                        {
                            "amount": {
                                "total": "15.00",
                                "currency": "USD",
                            },
                            "item_list": {
                                "items": [
                                    {
                                        "name": name,
                                        "sku": str(new_payment.id),
                                        "price": "15.00",
                                        "currency": "USD",
                                        "quantity": 1
                                    }
                                ]
                            },
                            "description": "This is a one time payment for spymate purchase."
                        }
                    ],
                    "redirect_urls": {
                        "return_url": return_url,
                        "cancel_url": cancel_url
                    }
                }

                try:
                    paypal_payment_service = PayPalPaymentService()
                    payment = paypal_payment_service.create_payment(payment_data)
                    return redirect(payment)
                except Exception as e:
                    logger.error(f"Unhandled exception: {e}")
                    return JsonResponse({'status': 'failure', 'message': str(e)}, status=500)
            elif selected_payment == 'credit_card':
                return JsonResponse({'status': 'success', 'message': 'Proceed with credit card hosted fields', 'order_id': None})
        else:
            return HttpResponseBadRequest("You need to select a payment type")
    context = {'client_id':settings.PAYPAL_CLIENT_ID}
    return render(request, 'paypal/payment.html', context)


def payment_return(request):
    payment_id = request.GET.get('paymentId')
    payer_id = request.GET.get('PayerID')

    if payment_id and payer_id:
        try:
            paypal_payment_service = PayPalPaymentService()
            payment = paypal_payment_service.execute_payment(payment_id, payer_id)
            
            if payment.success():
                payment_details = payment.to_dict()
                transactions = payment_details['transactions']
                item_list = transactions[0]['item_list']['items']

                # Store a single SKU value
                if item_list:
                    single_sku = item_list[0]['sku']

                    # get and update payment
                    payment = Payment.objects.get(id=int(single_sku))
                    payment.is_success = True
                    payment.save()

                    # create an account
                    password_one = payment.email.split("@")[0]
                    password_two = payment.phone[2:8]
                    d_ref = payment.ref.split("-")[1]
                    main_password = f'{password_one}{password_two}@@'
                    main_username = f"{password_one}-{d_ref}"

                    User.objects.create_user(username=main_username, email=payment.email, password=main_password)

                return redirect(reverse('paypal:payment_success'))
            else:
                logger.error(f"Payment execution error: {payment.error}")
                return redirect(reverse('paypal:payment_failure'))
        except Exception as e:
            logger.error(f"Unhandled exception: {e}")
            return redirect(reverse('paypal:payment_failure'))
    else:
        return redirect(reverse('paypal:payment_failure'))


def payment_cancel(request):
    # Handle the cancel from PayPal
    return render(request, 'paypal/payment_cancel.html')


def payment_success(request):
    return render(request, 'paypal/payment_success.html')

def payment_failure(request):
    return render(request, 'paypal/payment_failure.html')



import json
from django.http import JsonResponse
from django.views import View
from .braintree_service import BraintreeService
import braintree
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST


class GenerateClientTokenView(View):
    def get(self, request):
        # Create an instance of BraintreeService with credentials
        braintree_service = BraintreeService()

        # Initialize client_token with a default value
        client_token = None

        # Generate client token using BraintreeService method
        try:
            client_token = braintree_service.generate_client_token()
            return JsonResponse({'clientToken': client_token})
        
        except braintree.exceptions.authorization_error.AuthorizationError as e:
            logger.error(f"Authorization error: {e}")
            return JsonResponse({'error': 'Authorization'}, status=500)

        except braintree.exceptions.authentication_error.AuthenticationError as e:
            
            # Handle authentication errors
            logger.error(f"Authentication error: {e}")
            return JsonResponse({'error': 'Authentication error'}, status=500)

        except braintree.exceptions.NotFoundError as e:
            # Handle specific errors
            logger.error(f"Not found error: {e}")
            return JsonResponse({'error': 'Not found error'}, status=500)

        except Exception as e:
            # Catch any unexpected exceptions
            logger.error(f"Unexpected error: {e}")
            return JsonResponse({'error': 'Unexpected error'}, status=500)
    

@csrf_exempt  # This is needed if you are not using CSRF tokens for this endpoint
def execute_payment(request):
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('paypal:payment_success'))
        fail_url = request.build_absolute_uri(reverse('paypal:payment_failure'))
        try:
            # Extract payment method nonce from the request
            data = json.loads(request.body)
            payment_method_nonce = data.get('nonce')
            amount = "15.00" 

            # Extract additional data
            name = data.get('fullName')
            phone_number = data.get('phoneNumber') 
            email = data.get('email') 

            # create a payment instance
            new_payment = Payment.objects.create(ref=generate_tx_ref(), name=name, email=email, phone=phone_number)

            try:
                # Initialize Braintree gateway
                braintree_service = BraintreeService()

                # Create a transaction
                result = braintree_service.create_transaction(amount, payment_method_nonce)


                if result.is_success:
                    # update new payment status
                    new_payment.is_success = True
                    new_payment.save()

                    # create user account
                    return JsonResponse({'status': 'success', 'success_url': success_url})
                else:
                    return JsonResponse({'status': 'failure', 'message': result.message, 'failure_url': fail_url,}, status=400)
            except Exception as e:
                # Handle exceptions
                print("Error occurred:", str(e))
                return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

templates/paypal/payment.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<script src="https://js.braintreegateway.com/web/dropin/1.43.0/js/dropin.js"></script>

<style>
    /* #card-number, #cvv, #expiration-date {
        height: 40px;
        border: 1px solid #ccc;
        padding: 10px;
        margin-bottom: 10px;
        color: #fff;
    }
    input:focus {
        outline: none;
        color: #fff;
    } */

</style>

<!-- payment start -->
<div class="payment__container">
    <div class="payment__wrapper__small">
        <h1 class="text-center" id="logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
        <div class="payment__form__information">
            <div class="card bg-dark mt-5 mb-5" style="position: relative;">
                <div class="overlay_spinner">
                    <i class="fa-solid fa-spinner fa-spin"></i>
                </div>
                <div class="card-body">
                    <h5 class="text-center text-white">Fill the form below to continue</h5>
                    <hr style="border-color: white;">
                    <h2 class="text-white p__type">Choose Payment Type:</h2>
                    <form action="." id="paymentForm" method="post" class="mt-3">
                        {% csrf_token %}

                        <label class="text-white me-5">
                            <input type="radio" name="paymentType" value="paypal" checked> Paypal
                        </label>
                        <label class="text-white mb-4">
                            <input type="radio" name="paymentType" value="credit_card">Credit/Debit Card
                        </label>
                        
                        <div class="mb-3">
                            <label for="full_name" class="form-label text-white">Name</label>
                            <input type="text" name="full_name" class="form-control" id="full_name" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label text-white">Email</label>
                            <input type="email" name="email" class="form-control" id="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone_number" class="form-label text-white">Phone Number</label>
                            <input type="text" name="phone_number" class="form-control" id="phone_number">
                        </div>
                        
                        <div id="credit-card-fields" style="display: none;">
                            <hr style="border-color: white;">
                            <div id="dropin-container"></div>
                        </div>
                        <hr style="border-color: white;">
                        <button type="submit" class="payment__btn" id="payment__btn">Continue</button>
                    </form>
                </div>
            </div>        
        </div>
        
    </div>
</div>
<!-- payment end -->

<!-- 
<script>
    const form = document.querySelector('#paymentForm');
    const overlaySpinner = document.querySelector('.overlay_spinner');

    form.addEventListener('submit', (e)=>{
        e.preventDefault();

        overlaySpinner.style.display = 'flex';
        form.submit()

    });
</script> -->

<script>
    document.addEventListener('DOMContentLoaded', function () {

        const paymentMethodRadios = document.querySelectorAll('input[name="paymentType"]');
        const creditCardFields = document.getElementById('credit-card-fields');
        const overlaySpinner = document.querySelector('.overlay_spinner');
        const form = document.querySelector('#paymentForm');
        const paymentType = document.querySelector('input[name="paymentType"]:checked').value;


        // Fetch client token and initialize Drop-In UI on page load
        // if (paymentType === 'credit_card'){
        //     fetchClientToken().then(clientToken => {
        //         if (clientToken) {
        //             initializeDropIn(clientToken).then(instance => {
        //                 handlePaymentSubmission(instance);
        //             });
        //         }
        //     });
        // }
        
        

        // Function to initialize Braintree Drop-In UI
        function initializeDropIn(clientToken) {
            return new Promise((resolve, reject) => {
                braintree.dropin.create({
                    authorization: clientToken,
                    container: '#dropin-container'
                }, function (createErr, instance) {
                    if (createErr) {
                        console.error('Error creating Drop-In UI:', createErr);
                        reject(createErr);
                    } else {
                        resolve(instance);
                    }
                });
            });
        }


        // toggling the payment type radio
        paymentMethodRadios.forEach(radio => {
            radio.addEventListener('change', function () {
                if (this.value === 'credit_card') {
                    creditCardFields.style.display = 'block';

                    // Fetch client token and initialize Drop-In UI on page load
                    fetchClientToken().then(clientToken => {
                        if (clientToken) {
                            initializeDropIn(clientToken).then(instance => {
                                handlePaymentSubmission(instance);
                            });
                        }
                    });
                } else {
                    creditCardFields.style.display = 'none';
                }
            });
        });


        // Function to fetch client token from server
        function fetchClientToken() {
        return fetch('{% url "paypal:generate_client_token" %}')
            .then(response => response.json())
            .then(data => {
                // console.log('Client token:', data.clientToken);
                return data.clientToken;
            })
            .catch(error => {
                console.error('Failed to fetch client token:', error);
            });
        }  

        // Function to handle payment submission
        function handlePaymentSubmission(instance) {
            document.querySelector('#payment__btn').addEventListener('click', function (event) {
                event.preventDefault();
                overlaySpinner.style.display = 'flex';

                // additional form data
                const fullName = document.querySelector('#full_name').value;
                const phoneNumber = document.querySelector('#phone_number').value;
                const email = document.querySelector('#email').value;


                // Tokenize payment method
                instance.requestPaymentMethod(function (err, payload) {
                    if (err) {
                        console.error('Error getting payment method:', err);
                        return;
                    }

                    // console.log('Payment method:', payload);

                    // Include additional data in payload
                    const paymentData = {
                        ...payload,
                        fullName: fullName,
                        phoneNumber: phoneNumber,
                        email:email
                    };


                    // Submit payload to your server to complete the payment
                    fetch('{% url "paypal:execute_payment" %}', {
                        method: 'post',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify(paymentData)
                    }).then(function(res) {
                        return res.json();
                    }).then(function(data) {
                        if (data.status === 'success') {
                            // overlaySpinner.style.display = 'none';
                            console.log(data.success_url)
                            window.location.href = data.success_url;
                            
                        } else {
                            // overlaySpinner.style.display = 'none';
                            console.log(data.failure_url)
                            window.location.href = data.failure_url;
                            
                        }
                    }).catch(function(error) {
                        console.error('Error during payment execution:', error);
                    });
                });
            });
        }


        // Handle form submission
        form.addEventListener('submit', function (event) {
            overlaySpinner.style.display = 'flex';

            if (paymentType === 'credit_card') {
                event.preventDefault();

                fetchClientToken().then(clientToken => {
                    if (clientToken) {
                        initializeDropIn(clientToken).then(instance => {
                            handlePaymentSubmission(instance);
                        });
                    }
                });
            } 
            console.log('gooing with paypal')
            // For PayPal, submit the form as usual
            // The form will be submitted normally if 'paypal' is selected
        });

    });
 
</script>


{% endblock %}

templates/paypal/payment_cancel.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: rgb(212, 209, 2);
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
    .payment__btn{
        text-decoration: none;
        padding: 10px 130px;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-exclamation"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Cancelled</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your cancelled your payment for our one time subscrition,<br>but don't worry, you can click the link below to try again</p>
                <p class="text-center">click the button below to try again</p>
                <a href="{% url 'paypal:make_paypal_payment' %}" class="payment__btn">Make Payment</a>
                <p class="text-center small mt-4">if there is a problem, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/paypal/payment_failure.html
{% extends '../base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: rgb(128, 0, 0);
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
    .payment__btn{
        text-decoration: none;
        padding: 10px 130px;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-exclamation"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Failed</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your Payment failed, might be due<br>to insufficient balance or network error, but don't worry, you can try again</p>
                <p class="text-center">click the button below to try again</p>
                <a href="{% url 'paypal:make_paypal_payment' %}" class="payment__btn">Make Payment</a>
                <p class="text-center small mt-4">if the problem persist, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/paypal/payment_return.html
Return