frontend/urls.py
from django.urls import path

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.home, name='home'),
    path('sp1/payment/', views.make_payment, name='make_payment'),
    path('payement/details/ar-ab-ac', views.flutterwave_webhook, name='flutterwave_webhook'),
    path('sp1/payment/processing/', views.payment_processing, name='payment_processing'),
    path('sp1/payment/complete/', views.payment_complete, name='payment_complete'),
    path('sp1/payment/failed/', views.payment_failed, name='payment_failed'),
    path('api/ipapi-data/', views.fetch_ipapi_data, name='fetch_ipapi_data'),
    
]

paypal/urls.py
from django.urls import path

from . import views

app_name = 'paypal'

urlpatterns = [
    path('sp1/paypal-payment/', views.make_paypal_payment, name='make_paypal_payment'),
    path('sp1/payment-return/', views.payment_return, name='payment_return'),
    path('sp1/payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('sp1/payment-success/', views.payment_success, name='payment_success'),
    path('sp1/payment-failure/', views.payment_failure, name='payment_failure'),

    # braintree
    path('generate-client-token/', views.GenerateClientTokenView.as_view(), name='generate_client_token'),
    path('execute-payment/', views.execute_payment, name='execute_payment'),

]

paypalclient/urls.py
from django.urls import path

from . import views

app_name = 'paypalclient'

urlpatterns = [
    path('sp1/client-payment/', views.paypal_client_payment, name='paypal_client_payment'),
    path('sp1/capture-payment/', views.capture_payment, name='capture_payment'),
    path('sp1/payment-success/', views.payment_success, name='payment_success'),
    path('sp1/payment-failure/', views.payment_failure, name='payment_failure'),
]

spymate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('paypal/', include('paypal.urls', namespace='paypal')),
    path('paypalclient/', include('paypalclient.urls', namespace='paypalclient')),
]

templates/alert.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}


<!-- alert-{{ message.tags }} -->

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SpyMate | Monitor social media</title>

    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- boostrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- phone selector css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'frontend/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/css/payment.css' %}">

</head>
<body>
    <!-- loader -->
    <div class="overlay" id="overlay">
        <i class="fas fa-spinner fa-spin text-white"></i>
    </div>


    {% block content %}{% endblock %}
    {% include './footer.html' %}
    


    <!-- bootstrap js cdn -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Include intlTelInput library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.min.js"></script>

    <!-- Include utils.js script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.js"></script>

    <!-- custom js -->
    <script src="{% static 'frontend/js/app.js' %}"></script>

    <!-- google translate -->
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

    <script type="text/javascript">
        function googleTranslateElementInit() {
          new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
        }
    </script>
    

</body>
</html>

templates/footer.html
<style>
    .footer__container{
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .footer__wrapper__small{
        max-width: 400px;
        width: 100%;
        margin-inline: 30px;
    }
    .footer__wrapper__small p{
        font-size: 12px;
        color: rgb(124, 124, 124);
    }
</style>


<div class="footer__container">
    <div class="footer__wrapper__small">
        <p class="text-center">Privacy Policies - Terms of Use</p>
        <p class="text-center">SPY MATE - Copyright 2024</p>
        <center>
            <div id="google_translate_element"></div>
        </center>
    </div>
</div>

templates/index.html
{% extends './base.html' %}

{% load static %}

{% block content %}

<!-- page one start -->
<div class="all_first_page">
    <div class="wrapper__all">
        <div class="container py-5">
            <div class="inner__container">

                <h1 class="text-center" id="logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
                
                <!-- users -->
                <div class="active__users">
                    <div class="table__wrapper">
                        <table>
                            <tr>
                                <td class="wider-column">Current Active Users:</td>
                                <td>452,815</td>
                              </tr>
                        </table>
                    </div>
                    <div class="table__wrapper">
                        <table>
                            <tr>
                                <td class="wider-column">Devices Spied On:</td>
                                <td>2,983,410</td>
                            </tr>
                        </table>
                    </div>
                    
                </div>

                <!-- number input -->
                <div class="card shadow bg-dark w-100">
                    <div class="card-body">
                      
                        <h5 class="text-center text-white mb-5">Enter the phone number you want spy on:</h5>
                        <div class="error__message text-center text-danger mb-3">
                        </div>
                        <div class="phone___input">
                            <input type="tel" id="phone" name="phone">
                            <button type="submit" id="number_submit_btn" class="btn">Search</button>
                        </div>

                        <div class="os_logo">
                            <div class="apple__icon">
                                <a href=""><i class="fa-brands fa-apple"></i></a>
                                <p>Apple</p>
                            </div>
                            <div class="android__icon">
                                <a href=""><i class="fa-solid fa-robot"></i></a>
                                <p>Android</p>
                            </div>
                           
                        </div>   
                    </div>
                </div>
                

            </div>
            
        </div>
    </div>
</div>
<!-- page one end -->


<!-- page two start -->
<div class="wrapper__progress mb-5 pb-5" id="page_two">
    <div class="navbar__progress">
        <h1 class="text-center" id="progress_logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
        <div class="whatsapp__btn">
            <i class="fa-brands fa-whatsapp"></i>
            <p class="">Messages:</p>
            <i class="fa-solid fa-spinner fa-spin"></i>
        </div>
    </div>

    <!-- body of page 2 -->
    <div class="page2__body__wrapper mt-5" >
        <div class="page2__body bg-dark mt-5">
            <div class="spinner_new_me">
                <div class="kolo">
                    <i class="fa-solid fa-spinner fa-spin"></i>
                    <p class="text-center mt-4 text-white">Connecting to Whatsapp server ...  <span class="spinner_percent">0%</span></p>
                </div>
            </div>
            <div class="phone_number text-center mt-3">
                +12345677898
            </div>

            <p class="text-center mt-5 text-white fw-bold small">DOWNLOADING <span class="phane_number2"></span>  WHATSAPP MESSAGES, PLEASE WAIT... <span><i class=" ms-3 fa-solid fa-spinner fa-spin"></i></span> </p>

            <!-- progress bar here -->
            <div class="progress-container">
                <div class="progress-bar" id="progressBar"></div>
            </div>

            <div class="progress__info text-white text-center mb-5">
            </div>

            <!-- appearing list item -->
            <ul id="appearing__list" class="mb-5">
                <!-- <li class="list-item"><i class="fa-solid fa-circle-check"></i>Connecting to Whatsapp</li>
                <li class="list-item"><i class="fa-solid fa-circle-check"></i>Searching for Vulnerability</li>
                <li class="list-item"><i class="fa-solid fa-circle-check"></i>Detected a Loophole</li>
                <li class="list-item"><i class="fa-solid fa-circle-check"></i>Decrypting Information</li>
                <li class="list-item"><i class="fa-solid fa-circle-check"></i>Searching conversations, galleries and suspicious contacts...</li> -->
                <li class="list-item"><i class="fa-solid fa-circle-check"></i>Completed</li>
            </ul>
        </div>
    </div>
</div>
<!-- page two end -->

<!-- page three start -->
<div class="page__three">
    <div class="navbar__progress">
        <h1 class="text-center" id="progress_logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
        <div class="whatsapp__btn">
            <i class="fa-brands fa-whatsapp"></i>
            <p class="mt-3" style="font-size: 14px;">Messages:</p>
            <p class=" mt-3" style="font-size: 14px;" id="page_three_count_nav"></p>
        </div>
    </div>

    <h4 class="text-center text-white mt-5 mb-3">Free Consultation finished</h4>

    <div class="part__two__finished">
        <div class="part__two__wrapper">
            <div class="card bg-dark" id="sytem_found">
                <div class="card-body">
                    <h5 class="text-center text-white">We Found Total:</h5>

                    <div class="found__btn">
                        <p class="page_three_count_btn"></p>
                        <p>Messages:</p>
                        <!-- <i class="fa-solid fa-user-secret"></i> -->
                        <p class="unread__messages">17 Unread <br>messages
                        </p>
                    </div>

                    <h5 class="found__charges">We do not charge anything for consultation, it is <span>free</span>. But for those who want to take the next step and have <span>full access to spy on WhatsApp</span>, You must complete registration on this app by paying a one-time fee of <span>U$15.00</span> to keep the server running.</h5>

                    <a href="{% url 'paypalclient:paypal_client_payment' %}" class="register-btn"><i class="fa-solid fa-credit-card me-3"></i>Continue Registraion</a>
                </div>
            </div>
        </div>
        
    </div>
</div>
<!-- page three end -->

{% endblock %}

templates/login.html
{% extends './base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 50px;
        position: relative;
        border-radius: 5px;
    }
    .overlay_login{
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0,0,0,0.8);
        z-index: 10;
        display: none;
        justify-content: center;
        align-items: center;
        border-radius: 5px;
    }
    .overlay_login i{
        color: #fff;
        font-size: 30px;
    }
</style>
<div class="payment__container mb-5">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="overlay_login">
                <i class="fa-solid fa-spinner fa-spin"></i>
            </div>
            <div class="card-body">
                <h3 class="text-center">Login</h3>
                {% include './alert.html' %}
                <hr>
                <form action="." method="POST" id="loginForm">
                    {% csrf_token %}

                    <div class="mb-4">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username" required>
                    </div>
                    <div class="mb-4">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
                    </div>

                    <button type="submit" class="payment__btn">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    const form = document.querySelector('#loginForm');
    const overlaySpinner = document.querySelector('.overlay_login');

    form.addEventListener('submit', (e)=>{
        e.preventDefault();

        overlaySpinner.style.display = 'flex';
        form.submit();

    });
</script>
{% endblock %}

templates/payment.html
{% extends './base.html' %}

{% load static %}

{% block content %}

<!-- payment start -->
<div class="payment__container">
    <div class="payment__wrapper__small">
        <h1 class="text-center" id="logo"><i class="fa-solid fa-user-secret"></i> SPY<span>MATE</span></h1>
        <div class="payment__form__information">
            <div class="card bg-dark mt-5 mb-5" style="position: relative;">
                <div class="overlay_spinner">
                    <i class="fa-solid fa-spinner fa-spin"></i>
                </div>
                <div class="card-body">
                    <h5 class="text-center text-white">Fill the form below to continue</h5>
                    <hr style="border-color: white;">

                    <h2 class="text-white p__type">Choose Payment Type:</h2>
                    <form id="paymentForm" method="post" class="mt-3">
                        {% csrf_token %}
                        <label class="text-white me-5">
                          <input type="radio" name="paymentType" value="Card" checked> Card
                        </label>
                        <label class="text-white mb-4">
                          <input type="radio" name="paymentType" value="Bitcoin"> Bitcoin
                        </label>
                        
                        <div class="mb-3">
                            <label for="full_name" class="form-label text-white">Name</label>
                            <input type="text" name="full_name" class="form-control" id="full_name" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label text-white">Email</label>
                            <input type="email" name="email" class="form-control" id="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone_number" class="form-label text-white">Phone Number</label>
                            <input type="text" name="phone_number" class="form-control" id="phone_number">
                        </div>
                        <br>
                        <button type="submit" class="payment__btn">Continue</button>
                    </form>
                </div>
            </div>        
        </div>
        
    </div>
</div>
<!-- payment end -->

<script>
    const form = document.querySelector('#paymentForm');
    const overlaySpinner = document.querySelector('.overlay_spinner');

    form.addEventListener('submit', (e)=>{
        e.preventDefault();

        overlaySpinner.style.display = 'flex';
        form.submit()

    });
</script>

{% endblock %}

templates/payment_comlete.html
{% extends './base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: green;
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-check"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Successfull</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your Payment is successful, please check <br>your email for your login details to be able to continue using our service. </p>
                <p class="text-center">Thank you for trusting us.</p>
                <p class="text-center">If you don't receive an email, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/payment_failed.html
{% extends './base.html' %}

{% load static %}

{% block content %}
<style>
    .my_card{
        color: #fff;
        margin-top: 30px;
    }
    i{
        color: rgb(128, 0, 0);
        font-size: 50px;
        margin: 15px auto;
        float: center;
    }
    .payment__btn{
        text-decoration: none;
        padding: 10px 130px;
    }
</style>
<div class="payment__container">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="card-body">
                <center>
                    <i class="fa-solid fa-circle-exclamation"></i>
                </center>
                
                <p class="card-header text-center">One Time Subscription Failed</p>
                <hr style="border-color: #fff;">
                <p class="text-center text-white">Your Payment failed, might be due<br>to insufficient balance or network error, but don't worry, you can try again</p>
                <p class="text-center">click the button below to try again</p>
                <a href="{% url 'frontend:make_payment' %}" class="payment__btn">Make Payment</a>
                <p class="text-center small mt-4">if the problem persist, you can reach us through our customer care email: <a href="">customercare@spymate.app</a></p>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    document.addEventListener('DOMContentLoaded', function() {
        // Function to add query parameters and navigate to the new URL
        function addParamsAndNavigate() {
            // Check if the flag exists in session storage
            if (!sessionStorage.getItem('paramsAdded')) {
                var url = window.location.href; // Get the current URL
                var newParams = {
                    param1: 'value1',
                    param2: 'value2'
                };

                // Parse the current URL to extract query parameters
                var searchParams = new URLSearchParams(window.location.search);
                var existingParams = {};

                // Iterate over existing parameters and add them to the object
                for (var pair of searchParams.entries()) {
                    existingParams[pair[0]] = pair[1];
                }

                // Check if the parameters already exist in the URL
                var paramsExist = true;
                for (var key in newParams) {
                    if (!(key in existingParams && existingParams[key] === newParams[key])) {
                        paramsExist = false;
                        break;
                    }
                }

                // If parameters don't exist, add them and set the flag in session storage
                if (!paramsExist) {
                    var queryString = Object.keys(newParams).map(key => key + '=' + newParams[key]).join('&');
                    var newUrl = url + (url.includes('?') ? '&' : '?') + queryString;

                    // Navigate to the new URL
                    window.location.href = newUrl;

                    // Set the flag in session storage
                    sessionStorage.setItem('paramsAdded', 'true');
                }
            }
        }

        // Call the function when the page is visited or refreshed
        addParamsAndNavigate();
    });
</script> -->
    


{% endblock %}

templates/payment_processing.html
{% extends './base.html' %}

{% load static %}

{% block content %}
<style>
.my_card{
    display: flex;
    align-items: center;
    justify-content: center;
    height: 300px;
    margin-top: 60px;
}

.my_card i {
    color: #fff;
    font-size: 50px;
    text-align: center;
    margin-bottom: 20px;
}

.my_card p{
    font-size: 18px;
}
</style>

<div class="payment__container mb-4">
    <div class="payment__wrapper__small">
        <div class="card bg-dark my_card">
            <div class="content text-center">
                <i class="fa-solid fa-spinner fa-spin"></i>
                <p class="text-center text-white">Finalizing Payment......</p>
            </div>
        </div>
    </div>
</div>

<script>
    setTimeout(function() {
        location.reload();
    }, 5000); // Refresh after 5 seconds
</script>

{% endblock %}